-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/17/2017 12:55:25 AM
-- Target server version: 5.7.18
-- Please backup your target database before running this script 

CREATE DATABASE IF NOT EXISTS billing COLLATE utf8_general_ci;
USE billing;

# ..\PreDeployment.sql
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;



# ..\Tables\cards.Table.sql
--
-- Definition for table cards
--
CREATE TABLE cards (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(45) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;



# ..\Tables\installment.Table.sql
--
-- Definition for table installment
--
CREATE TABLE installment (
  Id int(11) NOT NULL AUTO_INCREMENT,
  purchaseId int(11) DEFAULT NULL,
  expirationDate date DEFAULT NULL,
  number int(11) DEFAULT NULL,
  price double DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 37
AVG_ROW_LENGTH = 1365
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;



# ..\Tables\person.Table.sql
--
-- Definition for table person
--
CREATE TABLE person (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(45) DEFAULT NULL,
  Phone varchar(45) DEFAULT NULL,
  Email varchar(95) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 305
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;



# ..\Tables\purchase.Table.sql
--
-- Definition for table purchase
--
CREATE TABLE purchase (
  Id int(11) NOT NULL AUTO_INCREMENT,
  date datetime NOT NULL,
  store varchar(255) DEFAULT NULL,
  value double DEFAULT NULL,
  installments int(11) DEFAULT NULL,
  initialDiscount int(11) DEFAULT NULL,
  cardId int(11) NOT NULL,
  personId int(11) NOT NULL,
  Description varchar(150) NOT NULL,
  PRIMARY KEY (Id),
  INDEX cardId_idx (cardId),
  INDEX personId_idx (personId),
  CONSTRAINT cardId FOREIGN KEY (cardId)
  REFERENCES cards (Id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT personId FOREIGN KEY (personId)
  REFERENCES person (Id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 6
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;



# ..\Procedures\person_add.Procedure.sql
DELIMITER $$

--
-- Definition for procedure person_add
--
CREATE PROCEDURE person_add (IN pName varchar(50), IN pPhone varchar(50), IN pEmail varchar(80))
BEGIN

  INSERT INTO billing.person (name, phone, Email)
    VALUE (pName, pPhone, pEmail);

END
$$
DELIMITER ;




# ..\Procedures\purchase_add.Procedure.sql
DELIMITER $$

--
-- Definition for procedure purchase_add
--
CREATE PROCEDURE purchase_add (IN pPersonId int, IN pDate date, IN pStore varchar(45), IN pValue double,
IN pInstallments int, IN pDiscountPercent int, IN pCardId int, IN pFirstExpDate date, IN pDescription varchar(150))
BEGIN

  INSERT INTO `billing`.`purchase` (`date`, `store`, `value`, `installments`, `initialDiscount`, `cardId`, `personId`, `Description`)
    VALUES (pDate, pStore, pValue, pInstallments, pDiscountPercent, pCardId, pPersonId, pDescription);

  SET @NewPurchaseId = LAST_INSERT_ID();
  SET @i = 0;
  SET @installmentValue = pValue / pInstallments;
  WHILE @i < pInstallments DO

    INSERT INTO `billing`.`installment` (`purchaseId`, `expirationDate`, `number`, `price`)
      VALUES (@NewPurchaseId, adddate(pFirstExpDate, INTERVAL @i MONTH), @i + 1, @installmentValue);

    SET @i = @i + 1;
  END WHILE;



END
$$
DELIMITER ;




# ..\PostDeployment.sql
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

