--
-- Definition for table cards
--
CREATE TABLE cards (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(45) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;
